# -*- coding: utf-8 -*-
"""prodigy_ds_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syffzfkKmReAnidWl8g0QZpDBLU0SVVA
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

a=pd.read_csv('Walmart.csv')

a.head()

a.info()

a.describe()

print(a.duplicated())

import matplotlib.pyplot as plt

a.loc[a['Weekly_Sales']<=0]

b=a.groupby(['Store','Date'])['Weekly_Sales'].max('Weekly_Sales')
b

a.isnull().sum()

Store = a.groupby(['Store']).agg({'Weekly_Sales':['min','max','sum']})
Store[:5]

df = a.drop(['Date'], axis=1)
df

plt.plot(kind='scatter')
plt.plot(a['Weekly_Sales'])
plt.plot(a['Temperature'].mean())
plt.xlabel('Temperature')
plt.ylabel('Weekly_Sales')

label=['non holiday week','holiday week']
color=['red','green']
plt.pie(a['Holiday_Flag'].value_counts(),labels=label,colors=color,startangle=90,shadow=True)
plt.legend()
plt.show

(a['Holiday_Flag']==0).sum()

(a['Holiday_Flag']==1).sum()

d = a.groupby(['Store']).agg({'Weekly_Sales':['mean'],'Holiday_Flag':['mean'],'Temperature':['mean'],'Fuel_Price': ['mean'], 'CPI':['mean'],'Unemployment':['mean']})
d

df=pd.DataFrame(d)
df2=df.round()
df3 = df2.drop(['Holiday_Flag'], axis=1)
df3

df3.columns

s2=a.nlargest(5,['Weekly_Sales'])
s2

s1=df3.nlargest(5,[('Weekly_Sales', 'mean')])
s1